apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  replicas: 1
  template:
    metadata:
      name: mysql-db
      labels:
        app: mysql-db
    spec:
      volumes:
        - name: mysql-db-store
          persistentVolumeClaim:
            claimName: mysql-db-pv-claim
      containers:
      - name: mysql-db
        image: mysql:5.7.20
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                key: mysql_user
                name: mysql-config
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: mysql_password
                name: mysql-config
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: mysql_database
                name: mysql-config
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: mysql_root_password
                name: mysql-config
        ports:
          - containerPort: 3306
            name: mysql-port
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-db-store
      restartPolicy: Always
  selector:
    matchLabels:
      app: mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
      nodePort: 30336
  type: NodePort
  clusterIP: "10.96.33.6"
